### ISSUE TITLE
Candidate titles

### ISSUE THREAD

**Issue by bvarjavand** [neurodata/graph-stats-book#1]
- Hands-on Network Statistics with Graspologic
 - Applied Statistical Connectomics

**Comment by jovo** [comment]
- Hands-on Network Data Science with Graspologic


On Tue, Sep 15, 2020 at 3:15 PM Bijan Varjavand <notifications@github.com>
wrote:

>
> *      External Email - Use Caution      *
>
>
>
>
>    - Hands-on Network Statistics with Graspologic
>    - Applied Statistical Connectomics
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fneurodata%2Fgraph-stats-book%2Fissues%2F1&data=02%7C01%7Cjovo%40jhu.edu%7C14e1feb6f408410a24b608d859abb5a1%7C9fa4f438b1e6473b803f86f8aedf0dec%7C0%7C0%7C637357941301868849&sdata=9w3XvVi%2BxBgqvDrbUEghOyisXtBa4BRs29KMre2JIaA%3D&reserved=0>,
> or unsubscribe
> <https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAAAKG4R7TYOL3N27YLDFKW3SF64M5ANCNFSM4RNTQ3NQ&data=02%7C01%7Cjovo%40jhu.edu%7C14e1feb6f408410a24b608d859abb5a1%7C9fa4f438b1e6473b803f86f8aedf0dec%7C0%7C0%7C637357941301878842&sdata=sGLGeOssH9LZKMUHZHig2BKarPDP6h%2FIJdeGeK019IM%3D&reserved=0>
> .
>


-- 
With gratitude,

Joshua T Vogelstein, PhD
neurodata.io | BME@JHU <https://www.bme.jhu.edu/> | dA/dt > 0 > dJ/dt
<https://twitter.com/neuro_data/status/1279067902658916352>
where A = appreciating, J = judging, and t = time.
How can I do better? <https://forms.gle/iEad8byD89eTPdYx6>
