### ISSUE TITLE
choose details for ch. 2 whole connectome

### ISSUE THREAD

**Issue by jovo** [neurodata/graph-stats-book#3]

**Comment by bdpedigo** [comment]
## Maggot data (Ch 2) outline [WIP]
- Plot/print some simple stats of the network
   - number of nodes
   - number of edges
   - density
   - total edge weight
   - degree distribution
   - edge weight distribution
- plot some kind of 3D network layout colored by some of the metadata
- take 1 hemisphere:
   - run ASE
   - show pairplot colored by... something
   - (maybe) show UMAP o ASE just for a simpler visualization
   - cluster and fit SBM/DCSBM models
- graph matching
   - take 2 hemispheres, graph match them, report accuracy
- models
   - use either predicted or known pairs to do "test" likelihood on the opposite hemisphere
- testing / alignment
   - go back to the embedding from before, but now embed the other hemisphere also
   - show different ways of doing the alignment using procrustes (with pairs) or seedless procrustes (no pairs) 
- multigraph
   - is it worth showing how we can embed the 4-channels jointly, or the 2 hemispheres, or all 2 x 4?
   - maybe could look at L/R joint embedding or aligned embedding and look for "aberrant" vertices?
