### ISSUE TITLE
schedule weekly meeting

### ISSUE THREAD

**Issue by jovo** [neurodata/graph-stats-book#4]

**Comment by jovo** [comment]
also invite weiwei

**Comment by ebridge2** [comment]
does this entail sending weiwei an email for weekly recurring meetings? Or just invite weiwei to be a member of the github project?

**Comment by jovo** [comment]
we'll send weiwei invite when we decide on timing

On Wed, Oct 7, 2020 at 1:19 PM Eric Bridgeford <notifications@github.com>
wrote:

>
> *      External Email - Use Caution      *
>
>
>
> does this entail sending weiwei an email regarding preference for weekly
> recurring meetings? Or just invite weiwei to be a member of the github
> project?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fneurodata%2Fgraph-stats-book%2Fissues%2F4%23issuecomment-705079220&data=02%7C01%7Cjovo%40jhu.edu%7C2aa183dda8ca4ac703bb08d86ae52aa1%7C9fa4f438b1e6473b803f86f8aedf0dec%7C0%7C0%7C637376879773882639&sdata=EkVWwEkZPgkc%2B4NVt191NV4CVy4sEIjX1jo8RUg4HaQ%3D&reserved=0>,
> or unsubscribe
> <https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAAAKG4QWIJWF24LJLXPXAC3SJSPKDANCNFSM4SHSMYVQ&data=02%7C01%7Cjovo%40jhu.edu%7C2aa183dda8ca4ac703bb08d86ae52aa1%7C9fa4f438b1e6473b803f86f8aedf0dec%7C0%7C0%7C637376879773882639&sdata=zhNfyr4ub49DI%2FoOAufFSvsxw8LN3GAfuxD9ekVGTNk%3D&reserved=0>
> .
>


-- 
With gratitude,

Joshua T Vogelstein, PhD
neurodata.io | BME@JHU <https://www.bme.jhu.edu/> | dA/dt > 0 > dJ/dt
<https://twitter.com/neuro_data/status/1279067902658916352>
where A = appreciating, J = judging, and t = time.
How can I do better? <https://forms.gle/iEad8byD89eTPdYx6>
