### ISSUE TITLE
make sure the version of graphbook_code in the docker is the most up-to-date

### ISSUE THREAD

**Issue by loftusa** [neurodata/graph-stats-book#60]
I just started a new `docker run` and it was using an old version of graphbook_code that was missing some imports. Checked that my `docker pull neurodata/graphstatsbook:0.0.1` was up-to-date (it was). Possibly I was just running the wrong image (e.g., `neurodata/graphstatsbook:latest`). Need to double-check.

**Comment by ebridge2** [comment]
Completed 6/30 on neurodata/graph-stats-book; no tags for 0.0.1
