### ISSUE TITLE
fix bibliographies

### ISSUE THREAD

**Issue by loftusa** [neurodata/graph-stats-book#72]
I have not been fixing the references section as I go through Lauren's edits. We need to go through the bibtex and make adjustments, for instance, below.

<img width="693" alt="Screenshot 2024-01-08 at 2 07 53 PM" src="https://github.com/neurodata/graph-stats-book/assets/12386450/cfa346de-a52b-4aa1-9283-75023e10a7bd">

**Comment by ebridge2** [comment]
Odd. this is literally a feature from their bibliography style they sent us in the .tex package they gave us. Will try to just fix globally because that's going to be a pita
