### ISSUE TITLE
Make sure that every Section of the book has an introductory paragraph

### ISSUE THREAD

**Issue by loftusa** [neurodata/graph-stats-book#73]
Lauren's recommendation throughout her comments, which I agree with.
Introductory paragraphs at the beginning of Sections should just summarize what we will talk about in that section, so that the reader knows what to expect and knows whether to skip it if they are just skimming for information.

**Comment by ebridge2** [comment]
Possible idea: Every section has a prettified "blurb" with section title, relevant background sections delineated, and intro paragraph.

**Comment by ebridge2** [comment]
Use formatted blurb from emails from CUP people.

**Comment by loftusa** [comment]
- [x] chapter 3
- [x] chapter 4
- [x] chapter 5
- [x] chapter 6
- [x] chapter 7
- [x] chapter 8
- [x] chapter 9

**Comment by loftusa** [comment]
- [x] chapter overviews list what we'll cover

**Comment by loftusa** [comment]
- [x] note: go back to sec:ch6:mle and finish the second paragraph

**Comment by loftusa** [comment]
Done with this. 

@ebridge2 can you carefully look over all of these? Then we can close it out
