### ISSUE TITLE
Go through overleaf and resolve / accept any edit/comment made by the other person

### ISSUE THREAD

**Issue by loftusa** [neurodata/graph-stats-book#92]
for alex: resolve/accept any comment made by eric
for eric:  resolve/accept any comment made by alex

Necessary to do prior to sending to copy-editor. This should be the very last thing we do, and probably we should set aside hours to do this together over a call before sending it off (and probably cracking open some hard-won beers)

**Comment by loftusa** [comment]
done with all of eric's coments up until now (aug 5)

**Comment by ebridge2** [comment]
closing this because we have other issues addressing this "closing out"
