### ISSUE TITLE
Figure reproduction

### ISSUE THREAD

**Issue by ebridge2** [neurodata/graph-stats-book#94]
1. Run through all of the jupyter notebooks in https://github.com/ebridge2/textbook_figs/. All execution should be done from the docker container indicated in Section 2.2 of the book.
  - Ensure that the figure that is produced approximately matches the figure in the book, up to randomness. If it does not match up to randomness, record the specific Figure number somewhere, as well as the corresponding section of the book.
2. Make a second notebook, many-for-1 with the existing notebooks (e.g., a chapter-wide notebook), corresponding to the code as-written in the book (e.g., copy/pasted exactly as-written in the book). Ensure that everything executes and that the code is consistent (up to plotting details, stylistic details, etc) with the code code in the section-by-section figure reproduction notebooks.

**Comment by loftusa** [comment]
Deliverable: a set of pngs that are name-to-name with figures in the manuscript, and corresponding svgs
