### ISSUE TITLE
Figure reproduction (1-to-1 with figures in the textbook)

### ISSUE THREAD

**Issue by ebridge2** [neurodata/graph-stats-book#97]
Go through every section of jupyter notebooks, and (exhaustively) ensure that the figures are nearly 1-to-1 (up to illustrator figures, and up to minor illustrator tweaking; e.g., some figures were produced separately, and then combined in illustrator, but the "meat" should be in python) between the textbook and what you produce when running the jupyter notebooks as-is (e.g., just pressing "go" on the whole thing). 

- [x] Chapter 2
- [x] Chapter 3
- [x] Chapter 4
- [x] Chapter 5
- [x] Chapter 6
- [x] Chapter 7
- [x] Chapter 8
- [x] Chapter 9

**Comment by ebridge2** [comment]
https://github.com/ebridge2/textbook_figs

**Comment by loftusa** [comment]
done
