### ISSUE TITLE
Code reproducibility in the textbook

### ISSUE THREAD

**Issue by ebridge2** [neurodata/graph-stats-book#98]
Ensure that the code from the textbook all runs, by taking code from each section, and pasting it into a jupyter notebook. While the code may contain minor incompleteness (e.g., omitting plotting, and other minor details at times), it should contain enough info that in your opinion a dedicated reader *could* reproduce the figure in the book.

- [x] Chapter 2
- [x] Chapter 3
- [x] Chapter 4
- [x] Chapter 5
- [x] Chapter 6
- [x] Chapter 7
- [x] Chapter 8
- [x] Chapter 9

**Comment by loftusa** [comment]
done
